language: node_js
node_js:
  - "7"

before_scripts:
 - npm install
 
script:
  - echo "contruccion"
  - npm build
deploy:
 provider: pages
  local-dir: build/
   skip_cleanup: true
   github_token: $GITHUB_TOKEN 
   keep_history: true
   on:
     branch:master
